"""
author: Rishi Babu
Comments generated by Claude
If doubtful or in the case of the a nuclear war, contact Rishi/Victoria
gnn.py — Tau vs Electron Neutrino Classifier (GNN)

Usage:
    # Train
    python gnn.py train \
        --tau_dbs /path/to/nutau.db \
        --nue_dbs /path/to/nue.db \
        --geo     /path/to/geometry_clean.csv \
        --max_events 5000 \
        --epochs 100 \
        --batch_size 32 \
        --save_dir /path/to/output

    # Export trained weights to ONNX
    python gnn.py export_onnx \
        --weights /path/to/output/gnn_weights_best.pt \
        --onnx_out /path/to/output/gnn_weights_best.onnx

"""

import argparse
import copy
import json
import math
import os
import random
import sqlite3
import sys
from itertools import product

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
from sklearn.metrics import roc_auc_score, roc_curve
from sklearn.model_selection import train_test_split
from torch.utils.data import Dataset
from tqdm import tqdm
from torch_cluster import knn_graph
from torch_geometric.data import Data, InMemoryDataset
from torch_geometric.loader import DataLoader
from torch_geometric.nn import TransformerConv, global_mean_pool

N_FEATURES = 13
SEQ_FEATURES = 6
FEATURE_NAMES = [
    "str_x", "str_y", "z_centroid", "z_asym",
    "t_mean", "t_asym", "q_log", "n_doms",
    "t_spread", "z_rel", "t_first", "q_frac",
    "log_energy",
]

def set_seed(seed=42):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)


def event_stream(db_file):
    """
    Stream events row by row from SQLite, joining truth info.
    Only events with energy > 5e4 are selected.
    Yields (event_no, pulse_rows, meta_dict) per event.
    meta_dict keys: energy
    """
    if not os.path.exists(db_file):
        raise FileNotFoundError(f"DB file not found: {db_file}")

    conn = sqlite3.connect(db_file)
    cols = [r[1] for r in conn.execute("PRAGMA table_info(truth)").fetchall()]

    if "energy" not in cols:
        raise RuntimeError(f"'energy' column missing from truth table in {db_file}")

    query = """
        SELECT p.event_no, p.dom_x, p.dom_y, p.dom_z, p.dom_time, p.charge,
            t.energy
        FROM   CleanedROIPulses p
        JOIN   truth            t ON p.event_no = t.event_no
        ORDER  BY p.event_no
    """

    cursor        = conn.cursor()
    cursor.execute(query)
    current_event = None
    buffer        = []
    meta_store    = {}

    for row in cursor:
        event_no = row[0]
        pulse    = row[:6]
        energy   = row[6]

        if current_event is None:
            current_event = event_no

        if event_no != current_event:
            yield current_event, buffer, meta_store.get(current_event, {})
            buffer        = []
            current_event = event_no

        buffer.append(pulse)

        if event_no not in meta_store:
            meta_store[event_no] = {"energy": float(energy)}

    if buffer:
        yield current_event, buffer, meta_store.get(current_event, {})

    conn.close()

def icecube_geom(geo_df):
    """Maps (rounded dom_x, dom_y, dom_z) -> string number."""
    geo_dict = {}
    for _, row in geo_df.iterrows():
        key = (round(float(row.dom_x), 1),
               round(float(row.dom_y), 1),
               round(float(row.dom_z), 1))
        geo_dict[key] = int(row.string)
    return geo_dict

def event_to_string_graph(rows, geo_dict, meta=None,
                           k=16, t_scale=500.0, xyz_scale=500.0,
                           charge_threshold=0.0):
    """
    Convert raw pulse rows for one event into a PyG Data object.
    Each node represents one detector string (not one DOM hit).

    Node features (13):
        0  str_x          string XY position x
        1  str_y          string XY position y
        2  z_centroid     charge-weighted Z centroid
        3  z_asym         (Q_top - Q_bot) / Q_total       <- tau signature
        4  t_mean         charge-weighted mean time
        5  t_asym         (Q_early - Q_late) / Q_total    <- tau signature
        6  q_log          log total charge on string
        7  n_doms         number of hit DOMs (normalised)
        8  t_spread       std of hit times
        9  z_rel          z_centroid relative to event centroid  <- tau
        10 t_first        time of first hit on string
        11 q_frac         string charge fraction of event
        12 log_energy     log10(energy) / 6  (from truth)
    """
    rows   = np.array(rows, dtype=object)
    x_hits = rows[:, 1].astype(float)
    y_hits = rows[:, 2].astype(float)
    z_hits = rows[:, 3].astype(float)
    t_hits = rows[:, 4].astype(float)
    q_hits = rows[:, 5].astype(float)

    # Time window: keep [t0, t0 + 1500 ns]
    t0   = t_hits.min()
    mask = (t_hits >= t0) & (t_hits <= t0 + 1500.0)
    x_hits, y_hits, z_hits = x_hits[mask], y_hits[mask], z_hits[mask]
    t_hits, q_hits          = t_hits[mask], q_hits[mask]
    t_hits                  = t_hits - t0

    # Charge threshold: keep only DOM hits with charge above threshold
    q_mask = q_hits > charge_threshold
    x_hits, y_hits, z_hits = x_hits[q_mask], y_hits[q_mask], z_hits[q_mask]
    t_hits, q_hits          = t_hits[q_mask], q_hits[q_mask]

    def _fallback():
        return Data(
            x          = torch.zeros((1, N_FEATURES), dtype=torch.float),
            edge_index = torch.zeros((2, 0),          dtype=torch.long),
        )

    if len(t_hits) < 2:
        return _fallback()

    # Map each hit to a string via geometry lookup
    string_ids = np.array([
        geo_dict.get((round(xi, 1), round(yi, 1), round(zi, 1)), -1)
        for xi, yi, zi in zip(x_hits, y_hits, z_hits)
    ])
    valid = string_ids >= 0
    x_hits, y_hits, z_hits     = x_hits[valid], y_hits[valid], z_hits[valid]
    t_hits, q_hits, string_ids = t_hits[valid], q_hits[valid], string_ids[valid]

    if len(t_hits) < 2:
        return _fallback()

    q_total    = q_hits.sum() + 1e-6
    z_q_center = np.sum(q_hits * z_hits) / q_total
    log_energy = np.log10(max(float(meta.get("energy", 1.0)), 1.0)) / 6.0 \
                 if meta else 0.0

    node_feats     = []
    unique_strings = np.unique(string_ids)

    for s in unique_strings:
        mask_s  = string_ids == s
        q_s     = q_hits[mask_s]
        t_s     = t_hits[mask_s]
        z_s     = z_hits[mask_s]
        x_s     = x_hits[mask_s]
        y_s     = y_hits[mask_s]
        q_sum_s = q_s.sum() + 1e-6

        str_x      = x_s[0] / xyz_scale
        str_y      = y_s[0] / xyz_scale
        z_centroid = np.sum(q_s * z_s) / q_sum_s
        z_mid      = np.median(z_s)
        q_top      = q_s[z_s >= z_mid].sum()
        q_bot      = q_s[z_s <  z_mid].sum()
        z_asym     = (q_top - q_bot) / q_sum_s
        t_mean_s   = np.sum(q_s * t_s) / q_sum_s
        q_early    = q_s[t_s <= 750.0].sum()
        q_late     = q_s[t_s >  750.0].sum()
        t_asym     = (q_early - q_late) / q_sum_s
        q_log      = np.log1p(q_sum_s)
        n_doms     = len(np.unique(z_s)) / 60.0
        t_spread   = float(t_s.std()) / t_scale if len(t_s) > 1 else 0.0
        z_rel      = (z_centroid - z_q_center) / xyz_scale
        t_first    = float(t_s.min()) / t_scale
        q_frac     = q_sum_s / q_total
        
        node_feats.append([
            str_x,                  # 0
            str_y,                  # 1
            z_centroid / xyz_scale, # 2
            z_asym,                 # 3  <- tau signature
            t_mean_s / t_scale,     # 4
            t_asym,                 # 5  <- tau signature
            q_log,                  # 6
            n_doms,                 # 7
            t_spread,               # 8
            z_rel,                  # 9  <- tau signature
            t_first,                # 10
            q_frac,                 # 11
            log_energy,             # 12
        ])

    node_feats = np.array(node_feats, dtype=np.float32)
    x_tensor   = torch.tensor(node_feats, dtype=torch.float)
    # pos        = x_tensor[:, :2]
    # edge_index = knn_graph(pos, k=min(k, len(x_tensor) - 1), loop=False)
    # edge_index = knn_graph(pos, k=16, loop=False)
    pos        = x_tensor[:, [0, 1, 2]]
    # Current — no guard, crashes on small events
    edge_index = knn_graph(pos, k=16, loop=False)

    # Fix
    k_actual   = min(16, x_tensor.size(0) - 1)
    if k_actual < 1:
        return _fallback()
    edge_index = knn_graph(pos, k=k_actual, loop=False)
    
    return Data(x=x_tensor, edge_index=edge_index)

class TauDataloader(InMemoryDataset):
    def __init__(self, nue_dbs, tau_dbs, geo_dict,
                 max_events_per_class=None, charge_threshold=0.0):
        super().__init__()

        if isinstance(nue_dbs, str): nue_dbs = [nue_dbs]
        if isinstance(tau_dbs, str): tau_dbs = [tau_dbs]

        for path in nue_dbs + tau_dbs:
            if not os.path.exists(path):
                raise FileNotFoundError(f"DB file not found: {path}")

        data_list = []

        # --- nutau ---
        print(f"Loading tau events from {len(tau_dbs)} file(s)...")
        count = 0
        for db in tqdm(tau_dbs, desc="  tau files", unit="file"):
            for eid, rows, meta in tqdm(
                event_stream(db),
                desc=f"    {os.path.basename(db)}",
                unit="ev", leave=False
            ):
                if max_events_per_class and count >= max_events_per_class:
                    break
                g   = event_to_string_graph(
                    rows, geo_dict, meta=meta, charge_threshold=charge_threshold
                )
                g.y = torch.tensor([1.0])
                data_list.append(g)
                count += 1
            if max_events_per_class and count >= max_events_per_class:
                break
        print(f"  -> Loaded {count} tau events")

        # --- nue ---
        print(f"Loading nue events from {len(nue_dbs)} file(s)...")
        count = 0
        for db in tqdm(nue_dbs, desc="  nue files", unit="file"):
            for eid, rows, meta in tqdm(
                event_stream(db),
                desc=f"    {os.path.basename(db)}",
                unit="ev", leave=False
            ):
                if max_events_per_class and count >= max_events_per_class:
                    break
                g   = event_to_string_graph(
                    rows, geo_dict, meta=meta, charge_threshold=charge_threshold
                )
                g.y = torch.tensor([0.0])
                data_list.append(g)
                count += 1
            if max_events_per_class and count >= max_events_per_class:
                break
        print(f"  -> Loaded {count} nue events")

        if len(data_list) == 0:
            raise RuntimeError("Dataset is empty -- check DB paths and table names.")

        print("Collating dataset...")
        self.data, self.slices = self.collate(data_list)
        print(f"  -> Total: {len(data_list)} events")

def collate_hit_sequences(batch):
    lengths = [sample["x"].size(0) for sample in batch]
    max_len = max(lengths)
    feat_dim = batch[0]["x"].size(1)

    x = torch.zeros((len(batch), max_len, feat_dim), dtype=torch.float32)
    mask = torch.ones((len(batch), max_len), dtype=torch.bool)
    y = torch.zeros(len(batch), dtype=torch.float32)

    for i, sample in enumerate(batch):
        seq = sample["x"]
        length = seq.size(0)
        x[i, :length] = seq
        mask[i, :length] = False
        y[i] = sample["y"]

    return {"x": x, "padding_mask": mask, "y": y}

class SuperGNN(nn.Module):

    def __init__(self, hidden_dim=256, input_dim=N_FEATURES, dropout=0.4, num_layers=7):
        super().__init__()

        self.node_mlp = nn.Sequential(
            nn.Linear(input_dim, hidden_dim),
            nn.ReLU(),
            nn.BatchNorm1d(hidden_dim),
        )

        self.num_layers = num_layers
        self.convs = nn.ModuleList()
        self.bns = nn.ModuleList()
        for i in range(num_layers):
            in_dim = hidden_dim if i == 0 else hidden_dim * 4
            self.convs.append(TransformerConv(in_dim, hidden_dim, heads=4))
            self.bns.append(nn.BatchNorm1d(hidden_dim * 4))
        self.act = nn.ReLU()
        self.drop = nn.Dropout(dropout)

        # +1 for appended mean_q
        self.classifier = nn.Sequential(
            nn.Linear(hidden_dim * 4 + 1, 64),
            nn.ReLU(),
            nn.Dropout(dropout),
            nn.Linear(64, 1),
        )

    def forward(self, data, edge_index=None, batch=None):
        if isinstance(data, Data):
            x = data.x
            edge_index = data.edge_index
            batch = data.batch
        else:
            x = data
            if edge_index is None or batch is None:
                raise ValueError("edge_index and batch are required when Data is not provided")

        raw_x = x

        x = self.node_mlp(x)
        for conv, bn in zip(self.convs, self.bns):
            x = self.drop(self.act(bn(conv(x, edge_index))))

        x = global_mean_pool(x, batch)
        mean_q = global_mean_pool(raw_x[:, 6:7], batch)  # feat 6 = q_log

        return self.classifier(torch.cat([x, mean_q], dim=1)).squeeze(1)

def evaluator(model, loader, criterion, device):
    model.eval()
    preds, trues = [], []
    total_loss   = 0.0

    with torch.no_grad():
        for batch in loader:
            batch   = batch.to(device)
            logits  = model(batch)
            targets = batch.y.view(-1)
            loss    = criterion(logits, targets)
            total_loss += loss.item() * batch.num_graphs
            preds.extend(torch.sigmoid(logits).cpu().numpy())
            trues.extend(targets.cpu().numpy())

    avg_loss = total_loss / len(loader.dataset)
    auc = roc_auc_score(trues, preds) if len(np.unique(trues)) >= 2 else float("nan")
    return avg_loss, auc, np.array(preds), np.array(trues)

def loss_schedule(optimizer, warmup_epochs, total_epochs, steps_per_epoch):
    """
    Step-level scheduler:
      - Linear warmup for `warmup_epochs` epochs  (lr: 0 -> peak)
      - Cosine decay for remaining epochs          (lr: peak -> 0)
    Call scheduler.step() once per batch.
    """
    warmup_steps = warmup_epochs * steps_per_epoch
    total_steps  = total_epochs  * steps_per_epoch

    def lr_lambda(current_step):
        if current_step < warmup_steps:
            return float(current_step) / float(max(1, warmup_steps))
        progress = float(current_step - warmup_steps) / float(
            max(1, total_steps - warmup_steps)
        )
        return max(0.0, 0.5 * (1.0 + np.cos(np.pi * progress)))

    return torch.optim.lr_scheduler.LambdaLR(optimizer, lr_lambda)

def load_checkpoint(checkpoint_path, model, optimizer, scheduler, device):
    """
    Load training state from checkpoint.
    Returns: (start_epoch, best_val_auc, best_epoch, train_losses, val_losses, val_aucs, lr_history)
    """
    if not os.path.exists(checkpoint_path):
        raise FileNotFoundError(f"Checkpoint file not found: {checkpoint_path}")
    
    checkpoint = torch.load(checkpoint_path, map_location=device)
    model.load_state_dict(checkpoint["model_state_dict"])
    optimizer.load_state_dict(checkpoint["optimizer_state_dict"])
    scheduler.load_state_dict(checkpoint["scheduler_state_dict"])
    
    start_epoch = checkpoint.get("epoch", 0)
    best_val_auc = checkpoint.get("best_val_auc", -np.inf)
    best_epoch = checkpoint.get("best_epoch", -1)
    train_losses = checkpoint.get("train_losses", [])
    val_losses = checkpoint.get("val_losses", [])
    val_aucs = checkpoint.get("val_aucs", [])
    lr_history = checkpoint.get("lr_history", [])
    
    print(f"Resumed from checkpoint: epoch {start_epoch}, best AUC: {best_val_auc:.4f} @ epoch {best_epoch}")
    return start_epoch, best_val_auc, best_epoch, train_losses, val_losses, val_aucs, lr_history

def load_model_weights(weights_path, model, device):
    """Load either a raw state_dict .pt file or a training checkpoint."""
    if not os.path.exists(weights_path):
        raise FileNotFoundError(f"Weights file not found: {weights_path}")

    payload = torch.load(weights_path, map_location=device)
    if isinstance(payload, dict) and "model_state_dict" in payload:
        state_dict = payload["model_state_dict"]
    elif isinstance(payload, dict):
        state_dict = payload
    else:
        raise RuntimeError(f"Unsupported weight file format: {weights_path}")

    model.load_state_dict(state_dict)
    return payload

def build_export_graph(num_nodes, device):
    if num_nodes < 2:
        raise ValueError("--num_nodes must be at least 2 for ONNX export")

    x = torch.zeros((num_nodes, N_FEATURES), dtype=torch.float32, device=device)
    src = torch.arange(num_nodes - 1, dtype=torch.long, device=device)
    dst = src + 1
    edge_index = torch.stack([
        torch.cat([src, dst]),
        torch.cat([dst, src]),
    ], dim=0)
    batch = torch.zeros(num_nodes, dtype=torch.long, device=device)
    return x, edge_index, batch

def export_onnx(args):
    device = torch.device("cpu")
    # Try to load config from checkpoint if available
    config = None
    if args.weights.endswith(".pt"):
        checkpoint = torch.load(args.weights, map_location=device)
        if isinstance(checkpoint, dict) and "config" in checkpoint:
            config = checkpoint["config"]
    # Priority: explicit args > config > defaults
    hidden_dim = getattr(args, "hidden_dim", None)
    if hidden_dim is None and config and "hidden_dim" in config:
        hidden_dim = config["hidden_dim"]
    if hidden_dim is None:
        hidden_dim = 256

    num_layers = getattr(args, "num_layers", None)
    if num_layers is None and config and "num_layers" in config:
        num_layers = config["num_layers"]
    if num_layers is None:
        num_layers = 7

    dropout = getattr(args, "dropout", None)
    if dropout is None and config and "dropout" in config:
        dropout = config["dropout"]
    if dropout is None:
        dropout = 0.4

    model = SuperGNN(
        input_dim=N_FEATURES,
        hidden_dim=hidden_dim,
        dropout=dropout,
        num_layers=num_layers
    ).to(device)
    load_model_weights(args.weights, model, device)
    model.eval()

    x, edge_index, batch = build_export_graph(args.num_nodes, device)

    onnx_out = args.onnx_out
    if onnx_out is None:
        root, _ = os.path.splitext(args.weights)
        onnx_out = root + ".onnx"

    out_dir = os.path.dirname(onnx_out)
    if out_dir:
        os.makedirs(out_dir, exist_ok=True)

    torch.onnx.export(
        model,
        (x, edge_index, batch),
        onnx_out,
        export_params=True,
        opset_version=args.opset,
        do_constant_folding=True,
        input_names=["x", "edge_index", "batch"],
        output_names=["logits"],
        dynamic_axes={
            "x": {0: "num_nodes"},
            "edge_index": {1: "num_edges"},
            "batch": {0: "num_nodes"},
            "logits": {0: "num_graphs"},
        },
    )
    print(f"Saved ONNX model -> {onnx_out}")

def prepare_training_data(args):
    set_seed(42)

    if not os.path.exists(args.geo):
        print(f"ERROR: geometry file not found: {args.geo}", file=sys.stderr)
        sys.exit(1)

    holdout_frac = args.val_frac + args.test_frac
    if holdout_frac <= 0.0 or holdout_frac >= 1.0:
        raise ValueError("val_frac + test_frac must be between 0 and 1")

    geo      = pd.read_csv(args.geo)
    geo_dict = icecube_geom(geo)
    print(f"Geometry: {len(geo_dict)} DOM entries")

    dataset = TauDataloader(
        nue_dbs              = args.nue_dbs,
        tau_dbs              = args.tau_dbs,
        geo_dict             = geo_dict,
        max_events_per_class = args.max_events,
        charge_threshold     = args.charge_threshold,
    )

    indices = np.arange(len(dataset))
    labels  = np.array([dataset[i].y.item() for i in range(len(dataset))])

    train_idx, holdout_idx = train_test_split(
        indices, test_size=holdout_frac, stratify=labels, random_state=42
    )
    val_idx, test_idx = train_test_split(
        holdout_idx,
        test_size    = args.test_frac / holdout_frac,
        stratify     = labels[holdout_idx],
        random_state = 42,
    )

    train_ds = dataset[train_idx.tolist()]
    val_ds   = dataset[val_idx.tolist()]
    test_ds  = dataset[test_idx.tolist()]
    print(f"Split -> train: {len(train_ds)}  val: {len(val_ds)}  test: {len(test_ds)}")

    return {
        "train_ds": train_ds,
        "val_ds": val_ds,
        "test_ds": test_ds,
        "train_idx": train_idx,
        "val_idx": val_idx,
        "test_idx": test_idx,
        "train_labels": labels[train_idx],
    }


def create_dataloaders(data_bundle, batch_size):
    num_workers = min(4, os.cpu_count() or 1)
    pin_memory = torch.cuda.is_available()

    train_loader = DataLoader(
        data_bundle["train_ds"],
        batch_size=batch_size,
        shuffle=True,
        num_workers=num_workers,
        pin_memory=pin_memory,
    )
    val_loader = DataLoader(
        data_bundle["val_ds"],
        batch_size=batch_size,
        num_workers=num_workers,
        pin_memory=pin_memory,
    )
    test_loader = DataLoader(
        data_bundle["test_ds"],
        batch_size=batch_size,
        num_workers=num_workers,
        pin_memory=pin_memory,
    )
    return train_loader, val_loader, test_loader


def save_training_plots(save_dir, train_losses, val_losses, val_aucs,
                        lr_history, best_val_auc, best_epoch,
                        test_auc, test_preds, test_trues):
    fig, axes = plt.subplots(1, 5, figsize=(25, 4), facecolor="black")
    fig.patch.set_facecolor("black")

    def style(ax, title, xlabel, ylabel):
        ax.set_facecolor("black")
        ax.tick_params(colors="white")
        for spine in ["bottom", "left"]:
            ax.spines[spine].set_color("gray")
        ax.spines["top"].set_visible(False)
        ax.spines["right"].set_visible(False)
        ax.set_title(title, color="white")
        ax.set_xlabel(xlabel, color="white")
        ax.set_ylabel(ylabel, color="white")

    axes[0].plot(train_losses, color="cyan", label="Train")
    axes[0].plot(val_losses, color="orange", label="Val")
    axes[0].legend(facecolor="black", labelcolor="white", edgecolor="gray")
    style(axes[0], "Loss", "Epoch", "BCE Loss")

    axes[1].plot(val_aucs, color="lime")
    axes[1].axhline(best_val_auc, color="white", lw=0.8, linestyle="--",
                    label=f"best={best_val_auc:.4f} @ ep{best_epoch}")
    axes[1].legend(facecolor="black", labelcolor="white", edgecolor="gray")
    style(axes[1], "Val AUC", "Epoch", "AUC")

    axes[2].plot(lr_history, color="yellow")
    axes[2].axvline(4, color="gray", lw=0.8, linestyle="--", label="warmup end")
    axes[2].legend(facecolor="black", labelcolor="white", edgecolor="gray")
    axes[2].set_yscale("log")
    style(axes[2], "Learning Rate", "Epoch", "LR (log scale)")

    fpr, tpr, _ = roc_curve(test_trues, test_preds)
    axes[3].plot(fpr, tpr, color="cyan", lw=2, label=f"AUC={test_auc:.3f}")
    axes[3].plot([0, 1], [0, 1], color="gray", lw=1, linestyle="--")
    axes[3].legend(facecolor="black", labelcolor="white", edgecolor="gray")
    style(axes[3], "ROC -- Test Set", "FPR", "TPR")

    sig_mask = test_trues >= 0.5
    bkg_mask = test_trues < 0.5
    bins = np.linspace(0.0, 1.0, 51)
    if np.any(sig_mask):
        axes[4].hist(
            test_preds[sig_mask],
            bins=bins,
            density=True,
            alpha=0.6,
            color="cyan",
            label="nutau (sig)",
        )
    if np.any(bkg_mask):
        axes[4].hist(
            test_preds[bkg_mask],
            bins=bins,
            density=True,
            alpha=0.6,
            color="orange",
            label="nue (bkg)",
        )
    axes[4].set_xlim(0.0, 1.0)
    axes[4].legend(facecolor="black", labelcolor="white", edgecolor="gray")
    style(axes[4], "Score Distribution", "Predicted score", "Density")

    plt.tight_layout()
    plot_path = os.path.join(save_dir, "training_curves.png")
    plt.savefig(plot_path, dpi=150, bbox_inches="tight", facecolor="black")
    plt.close()
    print(f"Saved curves     -> {plot_path}")


def run_training_job(args, data_bundle, save_dir, hidden_dim, num_layers,
                     dropout, epochs, patience, resume_from=None,
                     export_best_onnx=True, create_plots=True,
                     save_epoch_checkpoints=True, seed=42,
                     run_label=None):
    set_seed(seed)
    os.makedirs(save_dir, exist_ok=True)

    train_loader, val_loader, test_loader = create_dataloaders(
        data_bundle, args.batch_size
    )

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    label_prefix = f"[{run_label}] " if run_label else ""
    print(f"{label_prefix}Device: {device}")

    model = SuperGNN(
        input_dim=N_FEATURES,
        hidden_dim=hidden_dim,
        dropout=dropout,
        num_layers=num_layers,
    ).to(device)

    optimizer = torch.optim.AdamW(
        model.parameters(),
        lr=args.lr,
        weight_decay=args.weight_decay,
    )

    scheduler = loss_schedule(
        optimizer,
        warmup_epochs=5,
        total_epochs=epochs,
        steps_per_epoch=len(train_loader),
    )

    train_labels = data_bundle["train_labels"]
    n_pos = max(int((train_labels == 1).sum()), 1)
    n_neg = max(int((train_labels == 0).sum()), 1)
    pos_weight = torch.tensor([n_neg / n_pos], device=device, dtype=torch.float32)
    criterion = nn.BCEWithLogitsLoss(pos_weight=pos_weight)

    print(f"{label_prefix}Class balance   -- tau: {n_pos}  nue: {n_neg}  pos_weight: {n_neg / n_pos:.3f}")
    print(f"{label_prefix}LR schedule     -- warmup: 5 epochs, cosine decay over {epochs} epochs")
    print(f"{label_prefix}Peak LR         -- {args.lr:.2e}")

    best_val_auc = -np.inf
    best_val_loss = np.inf
    best_state = None
    best_epoch = -1
    epochs_no_gain = 0

    train_losses = []
    val_losses = []
    val_aucs = []
    lr_history = []

    weights_path = os.path.join(save_dir, "gnn_weights.pt")
    best_path = os.path.join(save_dir, "gnn_weights_best.pt")
    checkpoint_path = os.path.join(save_dir, "gnn_checkpoint.pt")

    start_epoch = 0
    if resume_from:
        start_epoch, best_val_auc, best_epoch, train_losses, val_losses, val_aucs, lr_history = load_checkpoint(
            resume_from, model, optimizer, scheduler, device
        )
        if len(val_losses) > 0:
            best_val_loss = float(np.min(val_losses))
        epochs_no_gain = max(0, start_epoch - best_epoch)

    epoch_desc = f"Epochs {run_label}" if run_label else "Epochs"
    epoch_pbar = tqdm(range(start_epoch, epochs), desc=epoch_desc, unit="epoch", position=0)
    for epoch in epoch_pbar:
        model.train()
        total_loss = 0.0

        batch_desc = f"  Train {epoch + 1:03d}"
        if run_label:
            batch_desc = f"  {run_label} {epoch + 1:03d}"
        batch_pbar = tqdm(
            train_loader,
            desc=batch_desc,
            unit="batch",
            position=1,
            leave=False,
        )
        for batch in batch_pbar:
            batch = batch.to(device)
            optimizer.zero_grad()
            logits = model(batch)
            targets = batch.y.view(-1)
            loss = criterion(logits, targets)
            loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
            optimizer.step()
            scheduler.step()
            total_loss += loss.item() * batch.num_graphs
            batch_pbar.set_postfix({"loss": f"{loss.item():.4f}"})

        current_lr = scheduler.get_last_lr()[0]
        train_loss = total_loss / len(train_loader.dataset)
        val_loss, val_auc, _, _ = evaluator(model, val_loader, criterion, device)

        train_losses.append(train_loss)
        val_losses.append(val_loss)
        val_aucs.append(val_auc if not np.isnan(val_auc) else 0.0)
        lr_history.append(current_lr)

        auc_improved = (not np.isnan(val_auc)) and (val_auc > best_val_auc)
        loss_improved = val_loss < best_val_loss

        if auc_improved:
            best_val_auc = val_auc
            best_state = copy.deepcopy(model.state_dict())
            best_epoch = epoch + 1
            torch.save(best_state, best_path)

        if loss_improved:
            best_val_loss = val_loss

        if auc_improved or loss_improved:
            epochs_no_gain = 0
        else:
            epochs_no_gain += 1

        val_auc_str = f"{val_auc:.4f}" if not np.isnan(val_auc) else "nan"
        epoch_pbar.set_postfix({
            "train": f"{train_loss:.4f}",
            "val_AUC": val_auc_str,
            "best_AUC": f"{best_val_auc:.4f}" if np.isfinite(best_val_auc) else "-inf",
            "lr": f"{current_lr:.2e}",
        })
        tqdm.write(
            f"{label_prefix}Epoch {epoch + 1:03d}/{epochs} | "
            f"Train: {train_loss:.4f} | "
            f"Val: {val_loss:.4f} | "
            f"AUC: {val_auc_str} | "
            f"Best: {best_val_auc:.4f} | "
            f"LR: {current_lr:.2e}"
        )

        run_config = dict(vars(args))
        run_config.update({
            "hidden_dim": hidden_dim,
            "num_layers": num_layers,
            "dropout": dropout,
            "epochs": epochs,
            "patience": patience,
        })

        epoch_checkpoint = {
            "epoch": epoch + 1,
            "model_state_dict": model.state_dict(),
            "optimizer_state_dict": optimizer.state_dict(),
            "scheduler_state_dict": scheduler.state_dict(),
            "best_val_auc": float(best_val_auc),
            "best_epoch": best_epoch,
            "train_losses": train_losses,
            "val_losses": val_losses,
            "val_aucs": val_aucs,
            "lr_history": lr_history,
            "train_idx": data_bundle["train_idx"],
            "val_idx": data_bundle["val_idx"],
            "test_idx": data_bundle["test_idx"],
            "config": run_config,
        }
        if save_epoch_checkpoints:
            epoch_ckpt_path = os.path.join(save_dir, f"gnn_checkpoint_epoch_{epoch + 1:03d}.pt")
            latest_ckpt_path = os.path.join(save_dir, "gnn_checkpoint_latest.pt")
            torch.save(epoch_checkpoint, epoch_ckpt_path)
            torch.save(epoch_checkpoint, latest_ckpt_path)

        if epochs_no_gain >= patience:
            tqdm.write(
                f"{label_prefix}Early stopping at epoch {epoch + 1} "
                f"(no val AUC or val loss improvement for {patience} epochs)"
            )
            break

    if best_state is None:
        best_state = copy.deepcopy(model.state_dict())
        best_epoch = max(start_epoch, len(train_losses))
        torch.save(best_state, best_path)

    model.load_state_dict(best_state)
    if np.isfinite(best_val_auc):
        print(f"\n{label_prefix}Restored best weights from epoch {best_epoch} (AUC={best_val_auc:.4f})")
    else:
        print(f"\n{label_prefix}Restored final weights (validation AUC unavailable)")

    torch.save(model.state_dict(), weights_path)
    run_config = dict(vars(args))
    run_config.update({
        "hidden_dim": hidden_dim,
        "num_layers": num_layers,
        "dropout": dropout,
        "epochs": epochs,
        "patience": patience,
    })
    checkpoint = {
        "epoch": best_epoch,
        "model_state_dict": model.state_dict(),
        "optimizer_state_dict": optimizer.state_dict(),
        "scheduler_state_dict": scheduler.state_dict(),
        "best_val_auc": float(best_val_auc),
        "best_epoch": best_epoch,
        "train_idx": data_bundle["train_idx"],
        "val_idx": data_bundle["val_idx"],
        "test_idx": data_bundle["test_idx"],
        "train_losses": train_losses,
        "val_losses": val_losses,
        "val_aucs": val_aucs,
        "lr_history": lr_history,
        "config": run_config,
    }
    torch.save(checkpoint, checkpoint_path)
    print(f"{label_prefix}Saved weights    -> {weights_path}")
    print(f"{label_prefix}Saved best       -> {best_path}")
    print(f"{label_prefix}Saved checkpoint -> {checkpoint_path}")

    test_loss, test_auc, test_preds, test_trues = evaluator(
        model, test_loader, criterion, device
    )
    print(f"{label_prefix}Test Loss: {test_loss:.4f} | Test AUC: {test_auc:.4f}")

    if create_plots:
        save_training_plots(
            save_dir,
            train_losses,
            val_losses,
            val_aucs,
            lr_history,
            best_val_auc,
            best_epoch,
            test_auc,
            test_preds,
            test_trues,
        )

    if export_best_onnx:
        class DummyArgs:
            pass

        onnx_args = DummyArgs()
        onnx_args.weights = best_path
        onnx_args.onnx_out = os.path.join(save_dir, "gnn_weights_best.onnx")
        onnx_args.num_nodes = 16
        onnx_args.opset = 17
        print(f"{label_prefix}Exporting best model to ONNX: {onnx_args.onnx_out}")
        export_onnx(onnx_args)

    return {
        "hidden_dim": hidden_dim,
        "num_layers": num_layers,
        "dropout": dropout,
        "best_val_auc": float(best_val_auc),
        "best_val_loss": float(best_val_loss),
        "best_epoch": best_epoch,
        "test_auc": float(test_auc),
        "test_loss": float(test_loss),
        "save_dir": save_dir,
        "best_path": best_path,
    }


def train(args):
    data_bundle = prepare_training_data(args)
    return run_training_job(
        args,
        data_bundle,
        save_dir=args.save_dir,
        hidden_dim=args.hidden_dim,
        num_layers=args.num_layers,
        dropout=args.dropout,
        epochs=args.epochs,
        patience=args.patience,
        resume_from=args.resume_from,
        export_best_onnx=True,
        create_plots=True,
        save_epoch_checkpoints=True,
        seed=42,
    )


def search_architectures(args):
    data_bundle = prepare_training_data(args)

    search_space = list(product(
        args.search_hidden_dims,
        args.search_num_layers,
        args.search_dropouts,
    ))
    if not search_space:
        raise ValueError("Search space is empty")

    trials_root = os.path.join(args.save_dir, "search_trials")
    os.makedirs(trials_root, exist_ok=True)

    results = []
    total_trials = len(search_space)
    print(f"Running architecture search over {total_trials} candidate(s)")
    for trial_idx, (hidden_dim, num_layers, dropout) in enumerate(search_space, start=1):
        trial_name = (
            f"trial_{trial_idx:02d}_h{hidden_dim}_l{num_layers}_d"
            f"{str(dropout).replace('.', 'p')}"
        )
        trial_dir = os.path.join(trials_root, trial_name)
        print(
            f"\n=== Trial {trial_idx}/{total_trials} | "
            f"hidden_dim={hidden_dim}, num_layers={num_layers}, dropout={dropout} ==="
        )
        trial_result = run_training_job(
            args,
            data_bundle,
            save_dir=trial_dir,
            hidden_dim=hidden_dim,
            num_layers=num_layers,
            dropout=dropout,
            epochs=args.search_epochs,
            patience=args.search_patience,
            resume_from=None,
            export_best_onnx=False,
            create_plots=False,
            save_epoch_checkpoints=False,
            seed=42 + trial_idx,
            run_label=trial_name,
        )
        trial_result["trial_name"] = trial_name
        results.append(trial_result)

    results_df = pd.DataFrame(results).sort_values(
        by=["best_val_auc", "best_val_loss"],
        ascending=[False, True],
    )
    results_path = os.path.join(args.save_dir, "architecture_search_results.csv")
    results_df.to_csv(results_path, index=False)
    print(f"Saved search summary -> {results_path}")

    best_row = results_df.iloc[0]
    best_config = {
        "hidden_dim": int(best_row["hidden_dim"]),
        "num_layers": int(best_row["num_layers"]),
        "dropout": float(best_row["dropout"]),
        "search_epochs": int(args.search_epochs),
        "search_patience": int(args.search_patience),
        "best_val_auc": float(best_row["best_val_auc"]),
        "best_val_loss": float(best_row["best_val_loss"]),
        "trial_name": best_row["trial_name"],
    }
    best_config_path = os.path.join(args.save_dir, "best_search_config.json")
    with open(best_config_path, "w", encoding="ascii") as handle:
        json.dump(best_config, handle, indent=2)
    print(f"Best search config  -> {best_config_path}")

    print(
        "\nRetraining best architecture with full schedule: "
        f"hidden_dim={best_config['hidden_dim']}, "
        f"num_layers={best_config['num_layers']}, "
        f"dropout={best_config['dropout']}"
    )
    final_result = run_training_job(
        args,
        data_bundle,
        save_dir=args.save_dir,
        hidden_dim=best_config["hidden_dim"],
        num_layers=best_config["num_layers"],
        dropout=best_config["dropout"],
        epochs=args.epochs,
        patience=args.patience,
        resume_from=None,
        export_best_onnx=True,
        create_plots=True,
        save_epoch_checkpoints=True,
        seed=42,
        run_label="best_search_model",
    )

    final_summary = {
        "search": best_config,
        "final_train": final_result,
    }
    final_summary_path = os.path.join(args.save_dir, "architecture_search_summary.json")
    with open(final_summary_path, "w", encoding="ascii") as handle:
        json.dump(final_summary, handle, indent=2)
    print(f"Saved final summary -> {final_summary_path}")
    return final_result


def run_diagnostics(args):
    set_seed(42)

    if not os.path.exists(args.geo):
        print(f"ERROR: geometry file not found: {args.geo}", file=sys.stderr)
        sys.exit(1)

    geo = pd.read_csv(args.geo)
    geo_dict = icecube_geom(geo)

    dataset = TauDataloader(
        nue_dbs=args.nue_dbs,
        tau_dbs=args.tau_dbs,
        geo_dict=geo_dict,
        max_events_per_class=args.max_events,
        charge_threshold=args.charge_threshold,
    )

    tau_indices = [i for i in range(len(dataset)) if dataset[i].y.item() == 1]
    nue_indices = [i for i in range(len(dataset)) if dataset[i].y.item() == 0]

    n_each = min(args.n_samples // 2, len(tau_indices), len(nue_indices))
    print(f"Sampling {n_each} tau + {n_each} nue events for feature diagnostics...")

    n_energy_each = min(args.n_energy_events // 2, len(tau_indices), len(nue_indices))
    print(f"Sampling {n_energy_each} tau + {n_energy_each} nue events for energy histogram...")

    def summarise(indices, n_take):
        feats = []
        for i in tqdm(indices[:n_take], desc="Summarise", leave=False):
            g = dataset[i]
            x = g.x.numpy()
            if x.shape[0] < 2:
                continue
            feats.append(np.concatenate([
                x.mean(axis=0),
                x.std(axis=0),
                x.max(axis=0),
            ]))
        return np.array(feats)

    # log_energy is feature index 12 and equals log10(E)/6
    def collect_energy(indices, n_take):
        energies = []
        for i in tqdm(indices[:n_take], desc="Collect energy", leave=False):
            g = dataset[i]
            x = g.x.numpy()
            if x.shape[0] < 1:
                continue
            log_e_norm = float(x[0, 12])
            energy = 10.0 ** (6.0 * log_e_norm)
            energies.append(energy)
        return np.array(energies, dtype=np.float64)

    tau_feats = summarise(tau_indices, n_each)
    nue_feats = summarise(nue_indices, n_each)

    if tau_feats.ndim < 2 or nue_feats.ndim < 2:
        print("ERROR: Not enough valid events for diagnostics.", file=sys.stderr)
        sys.exit(1)

    stat_names = (
        [f"mean_{f}" for f in FEATURE_NAMES] +
        [f"std_{f}" for f in FEATURE_NAMES] +
        [f"max_{f}" for f in FEATURE_NAMES]
    )

    sep_scores = []
    for i, name in enumerate(stat_names):
        t_mean = tau_feats[:, i].mean()
        n_mean = nue_feats[:, i].mean()
        t_std = tau_feats[:, i].std() + 1e-6
        n_std = nue_feats[:, i].std() + 1e-6
        sep = abs(t_mean - n_mean) / (0.5 * (t_std + n_std))
        sep_scores.append((sep, name, t_mean, n_mean))

    sep_scores.sort(reverse=True)

    print(f"\n{'Feature':<25} {'tau mean':>12} {'nue mean':>12} {'sep score':>12}")
    print("-" * 65)
    for sep, name, t_mean, n_mean in sep_scores[:15]:
        print(f"{name:<25} {t_mean:>12.4f} {n_mean:>12.4f} {sep:>12.4f}")

    # Feature separation figure
    fig, axes = plt.subplots(2, 4, figsize=(16, 8), facecolor="black")
    axes = axes.flatten()
    for idx, (sep, name, _, _) in enumerate(sep_scores[:8]):
        feat_idx = stat_names.index(name)
        ax = axes[idx]
        ax.hist(
            tau_feats[:, feat_idx], bins=40, alpha=0.6,
            color="cyan", label="nutau", density=True
        )
        ax.hist(
            nue_feats[:, feat_idx], bins=40, alpha=0.6,
            color="orange", label="nue", density=True
        )
        ax.set_title(f"{name}\nsep={sep:.3f}", color="white", fontsize=8)
        ax.set_facecolor("black")
        ax.tick_params(colors="white", labelsize=7)
        for spine in ["bottom", "left"]:
            ax.spines[spine].set_color("gray")
        ax.spines["top"].set_visible(False)
        ax.spines["right"].set_visible(False)
        legend = ax.legend(fontsize=7)
        for text in legend.get_texts():
            text.set_color("white")
        legend.get_frame().set_facecolor("black")
        legend.get_frame().set_edgecolor("gray")

    fig.suptitle("Top 8 separating features: nutau vs nue", color="white", fontsize=12)
    plt.tight_layout()

    os.makedirs(args.save_dir, exist_ok=True)
    out_path = os.path.join(args.save_dir, "feature_separation.png")
    plt.savefig(out_path, dpi=150, bbox_inches="tight", facecolor="black")
    plt.close()
    print(f"\nSaved -> {out_path}")

    # Energy histogram figure
    tau_e = collect_energy(tau_indices, n_energy_each)
    nue_e = collect_energy(nue_indices, n_energy_each)

    if len(tau_e) > 0 and len(nue_e) > 0:
        tau_loge = np.log10(np.clip(tau_e, 1.0, None))
        nue_loge = np.log10(np.clip(nue_e, 1.0, None))
        lo = min(tau_loge.min(), nue_loge.min())
        hi = max(tau_loge.max(), nue_loge.max())
        bins = np.linspace(lo, hi, 40)

        fig2, ax2 = plt.subplots(figsize=(8, 5), facecolor="black")
        fig2.patch.set_facecolor("black")
        ax2.set_facecolor("black")

        ax2.hist(tau_loge, bins=bins, alpha=0.6, density=True, color="cyan", label="nutau")
        ax2.hist(nue_loge, bins=bins, alpha=0.6, density=True, color="orange", label="nue")

        ax2.tick_params(colors="white")
        for spine in ["bottom", "left"]:
            ax2.spines[spine].set_color("gray")
        ax2.spines["top"].set_visible(False)
        ax2.spines["right"].set_visible(False)

        ax2.set_title("Energy distribution", color="white")
        ax2.set_xlabel("log10(Energy [GeV])", color="white")
        ax2.set_ylabel("Density", color="white")

        legend = ax2.legend(fontsize=9)
        for text in legend.get_texts():
            text.set_color("white")
        legend.get_frame().set_facecolor("black")
        legend.get_frame().set_edgecolor("gray")

        energy_out = os.path.join(args.save_dir, "energy_histogram.png")
        plt.tight_layout()
        plt.savefig(energy_out, dpi=150, bbox_inches="tight", facecolor="black")
        plt.close()
        print(f"Saved -> {energy_out}")
    else:
        print("Skipped energy histogram: not enough valid events.")

def plot_node_features(args):
    """
    Plot 1: Grid of per-node feature histograms (tau vs nue) for all 13 features.
    Plot 2: Pearson correlation heatmap of node features, one panel per class.
    """
    set_seed(42)

    geo      = pd.read_csv(args.geo)
    geo_dict = icecube_geom(geo)

    dataset = TauDataloader(
        nue_dbs              = args.nue_dbs,
        tau_dbs              = args.tau_dbs,
        geo_dict             = geo_dict,
        max_events_per_class = args.max_events,
        charge_threshold     = args.charge_threshold,
    )

    tau_nodes, nue_nodes = [], []
    for i in tqdm(range(len(dataset)), desc="Collecting node features"):
        g = dataset[i]
        x = g.x.numpy()           # shape (n_nodes, 13)
        if g.y.item() == 1:
            tau_nodes.append(x)
        else:
            nue_nodes.append(x)

    tau_arr = np.concatenate(tau_nodes, axis=0)   # (N_tau_nodes, 13)
    nue_arr = np.concatenate(nue_nodes, axis=0)   # (N_nue_nodes, 13)
    print(f"tau nodes: {tau_arr.shape[0]:,}   nue nodes: {nue_arr.shape[0]:,}")

    os.makedirs(args.save_dir, exist_ok=True)

    # ----------------------------------------------------------------
    # Plot 1 -- per-feature histograms  (4 cols × 4 rows, last row
    #           has 1 feature + AUC summary)
    # ----------------------------------------------------------------
    ncols = 4
    nrows = (N_FEATURES + ncols - 1) // ncols   # ceil division
    fig, axes = plt.subplots(nrows, ncols,
                              figsize=(5 * ncols, 4 * nrows),
                              facecolor="black")
    fig.patch.set_facecolor("black")
    axes_flat = axes.flatten()

    def _style(ax, title):
        ax.set_facecolor("black")
        ax.tick_params(colors="white", labelsize=8)
        for s in ["bottom", "left"]:
            ax.spines[s].set_color("gray")
        ax.spines["top"].set_visible(False)
        ax.spines["right"].set_visible(False)
        ax.set_title(title, color="white", fontsize=9)
        ax.set_ylabel("density", color="white", fontsize=8)

    for fi, name in enumerate(FEATURE_NAMES):
        ax = axes_flat[fi]
        t  = tau_arr[:, fi]
        n  = nue_arr[:, fi]

        # Clip to [1st, 99th] percentile to avoid extreme outlier bins
        lo = np.percentile(np.concatenate([t, n]), 1)
        hi = np.percentile(np.concatenate([t, n]), 99)
        bins = np.linspace(lo, hi, 50)

        ax.hist(t, bins=bins, density=True, alpha=0.65, color="cyan",   label="nutau")
        ax.hist(n, bins=bins, density=True, alpha=0.65, color="orange", label="nue")

        # Separation score (Fisher-style)
        sep = abs(t.mean() - n.mean()) / (0.5 * (t.std() + n.std()) + 1e-9)
        _style(ax, f"{name}  [sep={sep:.2f}]")

        legend = ax.legend(fontsize=7)
        for txt in legend.get_texts():
            txt.set_color("white")
        legend.get_frame().set_facecolor("black")
        legend.get_frame().set_edgecolor("gray")

    # Hide any unused subplots
    for fi in range(N_FEATURES, len(axes_flat)):
        axes_flat[fi].set_visible(False)

    fig.suptitle(
        "Per-node feature distributions: nutau (cyan) vs nue (orange)",
        color="white", fontsize=12, y=1.01,
    )
    plt.tight_layout()
    p1 = os.path.join(args.save_dir, "node_feature_histograms.png")
    plt.savefig(p1, dpi=150, bbox_inches="tight", facecolor="black")
    plt.close()
    print(f"Saved -> {p1}")

    # ----------------------------------------------------------------
    # Plot 2 -- correlation heatmaps (tau | nue side by side)
    # ----------------------------------------------------------------
    fig, axes = plt.subplots(1, 2, figsize=(18, 7), facecolor="black")
    fig.patch.set_facecolor("black")

    for ax, arr, label, cmap in zip(
        axes,
        [tau_arr, nue_arr],
        ["nutau", "nue"],
        ["PuBu", "OrRd"],
    ):
        corr = np.corrcoef(arr.T)   # (13, 13)

        im = ax.imshow(corr, vmin=-1, vmax=1, cmap=cmap, aspect="auto")
        plt.colorbar(im, ax=ax, fraction=0.046, pad=0.04)

        ax.set_xticks(range(N_FEATURES))
        ax.set_yticks(range(N_FEATURES))
        ax.set_xticklabels(FEATURE_NAMES, rotation=45, ha="right",
                           fontsize=7, color="white")
        ax.set_yticklabels(FEATURE_NAMES, fontsize=7, color="white")
        ax.set_facecolor("black")
        ax.tick_params(colors="white")
        ax.set_title(f"Feature correlations — {label}", color="white", fontsize=11)

        # Annotate cells with correlation value
        for i in range(N_FEATURES):
            for j in range(N_FEATURES):
                ax.text(j, i, f"{corr[i, j]:.2f}",
                        ha="center", va="center",
                        fontsize=5, color="white" if abs(corr[i, j]) < 0.7 else "black")

    plt.tight_layout()
    p2 = os.path.join(args.save_dir, "node_feature_correlations.png")
    plt.savefig(p2, dpi=150, bbox_inches="tight", facecolor="black")
    plt.close()
    print(f"Saved -> {p2}")

def parse_args():
    parser = argparse.ArgumentParser(
        description="Tau vs Electron Neutrino GNN Classifier",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    subparsers = parser.add_subparsers(dest="mode", required=True)

    # Shared arguments
    shared = argparse.ArgumentParser(add_help=False)
    shared.add_argument("--tau_dbs",    nargs="+", required=True,
                        help="Path(s) to tau SQLite DB files")
    shared.add_argument("--nue_dbs",    nargs="+", required=True,
                        help="Path(s) to nue SQLite DB files")
    shared.add_argument("--geo",
                        default="/mnt/scratch/baburish/doublepulse/stringv2/geometry_clean.csv",
                        help="Path to geometry_clean.csv")
    shared.add_argument("--max_events", type=int, default=None,
                        help="Max events per class (None = all)")
    shared.add_argument("--charge_threshold", type=float, default=0.0,
                        help="Keep only DOM hits with charge > threshold")
    shared.add_argument("--save_dir",   default="./output",
                        help="Directory to save outputs")

    # Train

    train_p = subparsers.add_parser("train", parents=[shared], help="Train the GNN")
    train_p.add_argument("--epochs", type=int, default=100)
    train_p.add_argument("--batch_size", type=int, default=32, help="Batch size (try 16, 32, 64)")
    train_p.add_argument("--lr", type=float, default=1e-3, help="Peak learning rate (try 1e-3, 5e-4, 1e-4)")
    train_p.add_argument("--val_frac", type=float, default=0.15)
    train_p.add_argument("--test_frac", type=float, default=0.15)
    train_p.add_argument("--patience", type=int, default=15, help="Early stopping patience (try 15, 25, 40)")
    train_p.add_argument("--resume_from", type=str, default=None, help="Path to checkpoint to resume training from")
    train_p.add_argument("--hidden_dim", type=int, default=256, help="Hidden dimension size (try 128, 192, 256, 384)")
    train_p.add_argument("--num_layers", type=int, default=7, help="Number of GNN layers (try 5, 7, 9)")
    train_p.add_argument("--dropout", type=float, default=0.4, help="Dropout rate (try 0.3, 0.4, 0.5)")
    train_p.add_argument("--weight_decay", type=float, default=1e-3, help="Weight decay for AdamW (try 1e-3, 5e-4, 1e-4)")

    search_p = subparsers.add_parser("search", parents=[shared], help="Search multiple GNN architectures and retrain the best")
    search_p.add_argument("--epochs", type=int, default=100, help="Full training epochs for the winning architecture")
    search_p.add_argument("--batch_size", type=int, default=32, help="Batch size used for search and final retraining")
    search_p.add_argument("--lr", type=float, default=1e-3, help="Peak learning rate")
    search_p.add_argument("--val_frac", type=float, default=0.15)
    search_p.add_argument("--test_frac", type=float, default=0.15)
    search_p.add_argument("--patience", type=int, default=15, help="Early stopping patience for final retraining")
    search_p.add_argument("--hidden_dim", type=int, default=256, help="Unused in search mode; final value is selected from the search space")
    search_p.add_argument("--num_layers", type=int, default=7, help="Unused in search mode; final value is selected from the search space")
    search_p.add_argument("--dropout", type=float, default=0.4, help="Unused in search mode; final value is selected from the search space")
    search_p.add_argument("--weight_decay", type=float, default=1e-3, help="Weight decay for AdamW")
    search_p.add_argument("--search_epochs", type=int, default=20, help="Epochs to use for each architecture trial")
    search_p.add_argument("--search_patience", type=int, default=8, help="Early stopping patience for each architecture trial")
    search_p.add_argument("--search_hidden_dims", nargs="+", type=int, default=[128, 256, 384], help="Hidden dimensions to try during search")
    search_p.add_argument("--search_num_layers", nargs="+", type=int, default=[5, 7, 9], help="Layer counts to try during search")
    search_p.add_argument("--search_dropouts", nargs="+", type=float, default=[0.3, 0.4, 0.5], help="Dropout values to try during search")

    # Transformer sequence model
    tr_p = subparsers.add_parser("train_transformer", parents=[shared],
                                  help="Train sequence transformer with Fourier-encoded hit features")
    tr_p.add_argument("--epochs",           type=int,   default=80)
    tr_p.add_argument("--batch_size",       type=int,   default=32)
    tr_p.add_argument("--lr",               type=float, default=1e-3)
    tr_p.add_argument("--val_frac",         type=float, default=0.15)
    tr_p.add_argument("--test_frac",        type=float, default=0.15)
    tr_p.add_argument("--patience",         type=int,   default=15)
    tr_p.add_argument("--max_hits",         type=int,   default=256,
                      help="Maximum number of detections per event sequence")
    tr_p.add_argument("--fourier_bands",    type=int,   default=8,
                      help="Number of Fourier frequency bands for continuous inputs")
    tr_p.add_argument("--d_model",          type=int,   default=128)
    tr_p.add_argument("--nhead",            type=int,   default=8)
    tr_p.add_argument("--num_layers",       type=int,   default=4)
    tr_p.add_argument("--dim_feedforward",  type=int,   default=256)
    tr_p.add_argument("--dropout",          type=float, default=0.2)
    tr_p.add_argument("--time_window_ns",   type=float, default=1500.0,
                      help="Time window [t0, t0+window] used to build hit sequences")

    # Export ONNX
    export_p = subparsers.add_parser("export_onnx",
                                     help="Export a trained .pt model to ONNX")
    export_p.add_argument("--weights", required=True,
                          help="Path to a saved model .pt file or checkpoint")
    export_p.add_argument("--onnx_out", default=None,
                          help="Output ONNX path (defaults to weights path with .onnx extension)")
    export_p.add_argument("--num_nodes", type=int, default=16,
                          help="Dummy node count used to trace the graph during export")
    export_p.add_argument("--opset", type=int, default=17,
                          help="ONNX opset version to use for export")
    export_p.add_argument("--hidden_dim", type=int, default=None,
                          help="Hidden dimension size (overrides checkpoint/config)")
    export_p.add_argument("--num_layers", type=int, default=None,
                          help="Number of GNN layers (overrides checkpoint/config)")
    export_p.add_argument("--dropout", type=float, default=None,
                          help="Dropout rate (overrides checkpoint/config)")

    # Diagnostics
    diag_p = subparsers.add_parser("diagnostics", parents=[shared],
                                    help="Run feature diagnostics")
    diag_p.add_argument("--n_samples", type=int, default=1000,
                        help="Total events to sample for diagnostics")
    diag_p.add_argument(
    "--n_energy_events",
    type=int,
    default=1000,
    help="Total events to sample for energy histogram",
)

    # Node feature plots
    subparsers.add_parser("plot_features", parents=[shared],
                          help="Plot per-node feature histograms and correlation heatmaps")

    return parser.parse_args()

if __name__ == "__main__":
    args = parse_args()
    print(f"Mode: {args.mode}")
    print(f"Args: {vars(args)}")

    if args.mode == "train":
        train(args)
    elif args.mode == "search":
        search_architectures(args)
    elif args.mode == "export_onnx":
        export_onnx(args)
    elif args.mode == "diagnostics":
        run_diagnostics(args)
    elif args.mode == "plot_features":
        plot_node_features(args)
    else:
        print(f"Unknown mode: {args.mode}", file=sys.stderr)
        sys.exit(1)